### ISSUE TITLE
SaveSet() and LoadSet() script event functions not working

### ISSUE THREAD

**Issue by trav-i** [Rottenbeer/ItemRack#116]
As the title says. The version of ItemRack that you ported over had these functions included, but they don't seem to be working right. When I called SaveSet(), I got an error that I was attempting to call a nil value.

**Comment by ronaldkunenborg** [comment]
Same here. The events that depend on it, don't work either. Like the Evocate event.

**Comment by Rottenbeer** [comment]
@trav-i how do you call them? Via a addon api?

**Comment by trav-i** [comment]
Yeah, through the WA scripting api. I think I see where you're going with this, I should call ItemRack.SaveSet() instead of SaveSet()?

**Comment by Rottenbeer** [comment]
I don't know, I did not test it, so I would need to have a look. Why are you using SaveSet in WA?

**Comment by ronaldkunenborg** [comment]
For me, because of https://www.wowinterface.com/forums/showthread.php?t=2596 . It gives the following evocation macro, which doesn't work at the moment in Itemrack Classic, and I would be a very happy mage if it did.

_This macro/event pair will swap in your spirit gear when you begin casting Evocation and then swap it out when you're done._

1. Make this macro to cast Evocation:
/script EVOCING=1 SaveSet("Spirit Gear") EquipSet("Spirit Gear")
/cast Evocation

2. Make this event:
Event: Mage:Evocation
Trigger: SPELLCAST_STOP
Delay: 1
Script:
if EVOCING and not CastingBarFrame.channeling then EVOCING=nil LoadSet() end
--[[Unequips a set when done casting Evocation]]

3. Associate the set "Spirit Gear" to the event. (can name it anything you want, doesn't need to be "Spirit Gear")

**Comment by Rottenbeer** [comment]
https://www.curseforge.com/wow/addons/itemrack-classic?page=2#comments
People claim that the Swimming Event works and there are also comments about the Evocation Event in the Thread, can you have a look there?
Did it work with one of the past versions or did it never work?

**Comment by ronaldkunenborg** [comment]
I didnt see anything in the 17 page thread. Anyway, I can get it to work "sort of" as follows (the EVENT in the above description was wrong, it's UNIT_SPELLCAST_CHANNEL_STOP now):

Make this macro to cast Evocation:
/itemrack equip "Spirit Gear"
/cast Evocation

Make this event:
Event: Mage:Evocation
Trigger: **UNIT_SPELLCAST_CHANNEL_STOP**
Delay: 1
Script:
if not CastingBarFrame.channeling then EquipSet("Standard") end

I think the page I referred to is either outdated or completely wrong.  I'll recheck tonight.

**Comment by Rottenbeer** [comment]
hmm your wowinterface thread is from 2005 and I had to change the default events and the event logic while I ported the addon to classic, so I'm not sure how to fix it tbh.
I neighter have a wow subscription nor a mage, so I appreciate if you can assist me here.

**Comment by ronaldkunenborg** [comment]
I'm an idiot and you're correct. Itemrack doesn't claim to support LoadSet and SaveSet in the readme.txt, and I hadn't checked the date on the thread either. It's very warm here :)

I'm now using the correct functions according to the readme I found in the code folder:
Make this macro to cast Evocation:
#showtooltip Evocation
/script EquipSet("SpiritGear")
/cast Evocation

Make this event:
Event: Mage:Evocation
Trigger: UNIT_SPELLCAST_CHANNEL_STOP
Delay: 1
Script:
if IsSetEquipped("SpiritGear") and not CastingBarFrame.channeling then  EquipSet("Standard") 
end

This works as intended.
