### ISSUE TITLE
Off hand doesnt equip with titans grip when using Polearm in Mainhand

### ISSUE THREAD

**Issue by brandofriva** [Rottenbeer/ItemRack#218]
Does not seem to equip off-hand when using a polearm in the mainhand slot and titans grip.
Tested with a few different weapon options.

**Comment by ThisIsMakena** [comment]
This is a bit of an edge case, due to the bug allowing TG to use polearms, I'm not sure it should be done in the addon because when (well, if), blizzard ever fixes the bug it'd then be an issue in the other direction.

You can add this functionality by commenting out, or removing, line 81 in ItemRack.lua, or just grab the attached file where I've made that change that allows it to work. (This is quick and dirty and will allow you to set a polearm in your offhand too, which you shouldn't do).
[ItemRack.zip](https://github.com/Rottenbeer/ItemRack/files/9834518/ItemRack.zip)

**Comment by Rottenbeer** [comment]
Please retest with 4.2
