### ISSUE TITLE
Depositing sets should only deposit unique items by default.

### ISSUE THREAD

**Issue by KevinTyrrell** [Rottenbeer/ItemRack#60]
I was overjoyed to find out that when you have a bank tab open, selecting a set withdraws the entire set from your bank. That was one of the most important features ItemRack could have given how important sets are to classes who fulfill multiple roles.

However when you have your bank open and your entire set is equipped/in your bags, changing to the set will **deposit the entire set into the bank**. This is extremely problematic because many of the items for that set are likely used on another. For example if I had a fire resistance set, I might have some tanking/dps pieces mixed in as well. If I deposit my fire resistance set, my DPS/Tanking/PvP sets are now red and cannot be used. The **only** way to fix this is to click on every set again to withdraw them from the bank. This is annoying but usable -- but once your bank reaches capacity, it ceases to be a workaround because your entire set cannot be deposited.

My recommendation would be that right clicking on a set from the selection window would deposit it in the way it currently works, while left clicking would only deposit items *unique to that set*.

**Comment by Rottenbeer** [comment]
I no longer maintain the addon, since I don't play WoW anymore, sorry.
I made a video that shows how interacting with the bank works in grneral: https://youtu.be/d_hrJKNtUfU
Also you can just select a few pieces for a set you don't need to select all the gear. See the original authors description of the addon OK curseforged for this.
