### ISSUE TITLE
No Bar where you can swap selected items

### ISSUE THREAD

**Issue by Shafferspank** [Rottenbeer/ItemRack#7]
There is no bar that's movable where you can select an item to be able to swap it to other items. Sort of like the trinket menu one. cant seem to get that to show up not sure if its not in yet or what. Thank you so much for porting this much appreciated!

**Comment by Rottenbeer** [comment]
![image](https://user-images.githubusercontent.com/2014982/64645254-bf929580-d414-11e9-9a9e-fa3c703c2298.png)
Like this?
/itemrack opt

**Comment by Flobberz** [comment]
![itemrack-setup](https://user-images.githubusercontent.com/34176960/64670595-61929c00-d46e-11e9-977b-8894f76b4c29.jpg)
Hes talking about this movable bar that you add slots to by alt clicking them in the menu.

**Comment by Flobberz** [comment]
Okay you can make the bar appear when alt clicking on the items in character menu instead of the addon menu, but it only shows the choices when right clicking it instead of just mouseovering, also I can't seem to change the bar from horizontal to vertical. Other than that I think it works like its supposed to.
